#!/usr/bin/env python3
"""Emit (or replace) a machine-verified implementation status block in AUDIT.md.

The block is fenced by ``<!-- status:begin -->`` / ``<!-- status:end -->``
sentinels and is regenerated on every invocation. Fields:

- ``revision`` — current git HEAD (short SHA);
- ``python`` — running interpreter version;
- ``schema_count`` — number of ``schemas/*.schema.json``;
- ``test_count`` — number of pytest tests collected (matching the local
  checkout; the runner pins ``tests/`` as the only test root);
- ``last_audit_revision`` — the commit SHA whose AUDIT.md is currently
  authoritative; read from the front-matter ``Implementation revision
  inspected: <sha>`` line and falling back to ``"unknown"`` if absent.

The script is idempotent: if the sentinels are present it replaces the
block between them; if absent it appends the block at the end of the
file. Manual prose above the sentinels is never touched.

Usage:

  python3 scripts/emit_implementation_status.py [--repository-root PATH]
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from platform import python_version

REPO_ROOT_DEFAULT = Path(__file__).resolve().parents[1]

BEGIN_SENTINEL = "<!-- status:begin -->"
END_SENTINEL = "<!-- status:end -->"

AUDIT_REVISION_RE = re.compile(
    r"^Implementation revision inspected:\s*([0-9a-f]{4,40})\s*$",
    re.MULTILINE,
)


def _git_short_sha(repository_root: Path) -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(repository_root),
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return "unknown"
    return out.decode("utf-8").strip() or "unknown"


def _audit_revision(audit_text: str) -> str:
    match = AUDIT_REVISION_RE.search(audit_text)
    return match.group(1) if match else "unknown"


def _schema_count(repository_root: Path) -> int:
    schemas_dir = repository_root / "schemas"
    if not schemas_dir.is_dir():
        return 0
    return sum(1 for _ in schemas_dir.glob("*.schema.json"))


def _test_count(repository_root: Path) -> int:
    """Collect tests in a subprocess and parse the count from output.

    Falls back to ``0`` if collection fails for any reason.
    """
    env = os.environ.copy()
    src = str(repository_root / "src")
    env["PYTHONPATH"] = src + os.pathsep + env.get("PYTHONPATH", "")
    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "pytest",
            "--collect-only",
            "-q",
            "--no-header",
            "--rootdir",
            str(repository_root),
            str(repository_root / "tests"),
        ],
        cwd=str(repository_root),
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    # The final summary line is typically ``"185 tests collected"``.
    for line in reversed(proc.stdout.splitlines()):
        m = re.search(r"(\d+)\s+tests?\s+collected", line)
        if m:
            return int(m.group(1))
        m = re.search(r"collected\s+(\d+)\s+items?", line)
        if m:
            return int(m.group(1))
    return 0


def build_status_block(repository_root: Path) -> str:
    """Build the markdown block (between sentinels) for the given repo."""
    audit_text = (repository_root / "AUDIT.md").read_text(encoding="utf-8")
    revision = _git_short_sha(repository_root)
    py_ver = python_version()
    schema_count = _schema_count(repository_root)
    test_count = _test_count(repository_root)
    last_audit = _audit_revision(audit_text)

    body = (
        f"- revision: `{revision}`\n"
        f"- python: `{py_ver}`\n"
        f"- schema_count: `{schema_count}`\n"
        f"- test_count: `{test_count}`\n"
        f"- last_audit_revision: `{last_audit}`\n"
    )
    return (
        f"{BEGIN_SENTINEL}\n"
        "<!--\n"
        "Machine-verified implementation status. Regenerated by\n"
        "`scripts/emit_implementation_status.py`. Do not edit by hand.\n"
        "-->\n"
        f"\n{body}\n"
        f"{END_SENTINEL}\n"
    )


def write_block(audit_path: Path, block: str) -> None:
    """Replace the status block if present, otherwise append."""
    text = audit_path.read_text(encoding="utf-8")
    if BEGIN_SENTINEL in text and END_SENTINEL in text:
        pattern = re.compile(
            rf"{re.escape(BEGIN_SENTINEL)}.*?{re.escape(END_SENTINEL)}\n?",
            re.DOTALL,
        )
        new_text = pattern.sub(lambda _m: block, text, count=1)
    else:
        sep = "\n\n" if not text.endswith("\n\n") else ""
        new_text = text + sep + block
    audit_path.write_text(new_text, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=REPO_ROOT_DEFAULT,
    )
    parser.add_argument(
        "--audit-path",
        type=Path,
        default=None,
        help="Path to AUDIT.md (default: <repository-root>/AUDIT.md).",
    )
    args = parser.parse_args(argv)

    audit_path = args.audit_path or args.repository_root / "AUDIT.md"
    block = build_status_block(args.repository_root)
    write_block(audit_path, block)
    print(f"updated status block in {audit_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())